/**
 * Document Model - Stores Information About Uploaded PDF Files
 * 
 * This file creates the "Documents" table in the database.
 * Each row represents one uploaded PDF document.
 */

import { DataTypes } from 'sequelize';
import { sequelize, User } from './User.js';

function parseJsonField(rawValue, fallbackValue) {
  if (!rawValue) {
    return fallbackValue;
  }

  try {
    return JSON.parse(rawValue);
  } catch (_error) {
    return fallbackValue;
  }
}

function stringifyJsonField(value, fallbackValue) {
  const safeValue = value ?? fallbackValue;
  return JSON.stringify(safeValue);
}

// --- DOCUMENT TABLE DEFINITION ---
const Document = sequelize.define('Document', {
    // Financial figures extracted by NLP microservice (array of objects)
    financialFigures: {
      type: DataTypes.TEXT,
      allowNull: true,
      get() {
        const value = this.getDataValue('financialFigures');
        return parseJsonField(value, []);
      },
      set(value) {
        const jsonValue = stringifyJsonField(value, []);
        this.setDataValue('financialFigures', jsonValue);
      }
    },

    // Named entities extracted by NLP microservice (array of objects)
    nlpEntities: {
      type: DataTypes.TEXT,
      allowNull: true,
      get() {
        const value = this.getDataValue('nlpEntities');
        return parseJsonField(value, []);
      },
      set(value) {
        const jsonValue = stringifyJsonField(value, []);
        this.setDataValue('nlpEntities', jsonValue);
      }
    },

    // Audit-style flags derived from extracted text (array of objects)
    auditFlags: {
      type: DataTypes.TEXT,
      allowNull: true,
      get() {
        const value = this.getDataValue('auditFlags');
        return parseJsonField(value, []);
      },
      set(value) {
        const jsonValue = stringifyJsonField(value, []);
        this.setDataValue('auditFlags', jsonValue);
      }
    },
  
  // Unique ID for each document 
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  
  // Original filename when user uploaded it 
  originalName: {
    type: DataTypes.STRING,
    allowNull: false
  },
  
  // Unique filename stored on server 
  filename: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true  // No two files can have the same stored filename
  },
  
  // Full path to file on server 
  filePath: {
    type: DataTypes.STRING,
    allowNull: false
  },
  
  // File size in bytes 
  fileSize: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  
  // ID of the user who uploaded this document
  userId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Users',  // Links to the Users table
      key: 'id'
    }
  },
  
  // When the document was uploaded 
  uploadDate: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW  // Automatically set to current time
  },

  // When the document should be deleted (6 months after upload) May change depending on what Helix says
  expiresAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  
  // --- NLP PROCESSING RESULTS ---
  
  // Raw text extracted from the PDF
  extractedText: {
    type: DataTypes.TEXT,  // TEXT allows for large amounts of text
    allowNull: true  // Optional - only filled after NLP processing
  },

  // Human-readable extractive summary generated by NLP service
  nlpSummary: {
    type: DataTypes.TEXT,
    allowNull: true
  },

  // Evaluation-ready metadata for ROUGE/BLEU scoring of generated summary
  nlpSummaryEvaluation: {
    type: DataTypes.TEXT,
    allowNull: true,
    get() {
      const value = this.getDataValue('nlpSummaryEvaluation');
      return parseJsonField(value, null);
    },
    set(value) {
      const jsonValue = stringifyJsonField(value, null);
      this.setDataValue('nlpSummaryEvaluation', jsonValue);
    }
  },

  // Explainability trace: shows which entities/rules drove NLP decisions
  nlpDecisionTrace: {
    type: DataTypes.TEXT,
    allowNull: true,
    get() {
      const value = this.getDataValue('nlpDecisionTrace');
      return parseJsonField(value, null);
    },
    set(value) {
      const jsonValue = stringifyJsonField(value, null);
      this.setDataValue('nlpDecisionTrace', jsonValue);
    }
  },
  
  // Processed tokens
  // Stored as JSON array
  processedTokens: {
    type: DataTypes.TEXT,
    allowNull: true,
    // Automatically convert between JSON string (database) and JavaScript array (code)
    get() {
      const value = this.getDataValue('processedTokens');
      return parseJsonField(value, null);
    },
    set(value) {
      const jsonValue = stringifyJsonField(value, null);
      this.setDataValue('processedTokens', jsonValue);
    }
  },
  
  // Word frequency data 
  // Stored as JSON object: 
  wordFrequency: {
    type: DataTypes.TEXT,
    allowNull: true,
    // Automatically convert between JSON string (database) and JavaScript object (code)
    get() {
      const value = this.getDataValue('wordFrequency');
      return parseJsonField(value, null);
    },
    set(value) {
      const jsonValue = stringifyJsonField(value, null);
      this.setDataValue('wordFrequency', jsonValue);
    }
  },
  
  // Top 20 most common words
  // Stored as JSON array
  topWords: {
    type: DataTypes.TEXT,
    allowNull: true,
    // Automatically convert between JSON string (database) and JavaScript object (code)
    get() {
      const value = this.getDataValue('topWords');
      return parseJsonField(value, null);
    },
    set(value) {
      const jsonValue = stringifyJsonField(value, null);
      this.setDataValue('topWords', jsonValue);
    }
  },
  
  // Flag to indicate if NLP processing has been completed
  nlpProcessed: {
    type: DataTypes.BOOLEAN,
    defaultValue: false  // Starts as false, set to true after NLP processing
  },

  // NLP Processing Timing Information
  nlpProcessingStartTime: {
    type: DataTypes.DATE,
    allowNull: true  // When NLP processing started
  },

  nlpProcessingEndTime: {
    type: DataTypes.DATE,
    allowNull: true  // When NLP processing completed
  },

  nlpProcessingDuration: {
    type: DataTypes.FLOAT,
    allowNull: true  // Processing duration in seconds
  },

  // NLP Processing Error Message (if processing failed)
  nlpError: {
    type: DataTypes.TEXT,
    allowNull: true  // Error message for failed processing, null if successful
  }
}, {
  tableName: 'documents',
  timestamps: true  // Automatically add createdAt and updatedAt fields
});


// --- DATABASE RELATIONSHIPS ---
// Paul Corey's Database Model came in handy here :)

// A Document belongs to one User 
Document.belongsTo(User, { foreignKey: 'userId' });

// A User can have many Documents
User.hasMany(Document, { foreignKey: 'userId' });

export default Document;
