import React from 'react';
import { styles } from './NLPAnalysis.styles';

// Renders summary-style sections near the top of the NLP report.
// This includes headline metrics, generated summary, timing, and extracted figures.
function NLPAnalysisOverviewSection({ nlpData, stats, summaryText, financialFigures }) {
  return (
    <>
      {/* High-level statistics used as an immediate document snapshot. */}
      <div style={styles.section}>
        <h3>
          <i className="bi bi-graph-up me-2"></i>
          Statistics
        </h3>
        <div style={styles.statsGrid}>
          <div style={styles.statCard}>
            <div style={styles.statValue}>{stats.textLength.toLocaleString()}</div>
            <div style={styles.statLabel}>Characters</div>
          </div>
          <div style={styles.statCard}>
            <div style={styles.statValue}>{stats.totalWords.toLocaleString()}</div>
            <div style={styles.statLabel}>Words</div>
          </div>
          <div style={styles.statCard}>
            <div style={styles.statValue}>{stats.uniqueWords.toLocaleString()}</div>
            <div style={styles.statLabel}>Unique Words</div>
          </div>
        </div>
      </div>

      {/* Extractive summary generated by the NLP backend. */}
      {summaryText && (
        <div style={styles.section}>
          <h3>
            <i className="bi bi-card-text me-2"></i>
            Executive Summary
          </h3>
          <div style={styles.summaryBox}>{summaryText}</div>
        </div>
      )}

      {/* Timing details for traceability of analysis runtime. */}
      {nlpData.timing && nlpData.timing.duration && (
        <div style={styles.section}>
          <h3>
            <i className="bi bi-clock-history me-2"></i>
            Processing Time
          </h3>
          <div style={styles.timingInfo}>
            <div style={styles.timingItem}>
              <span style={styles.timingLabel}>Duration:</span>
              <span style={styles.timingValue}>{nlpData.timing.duration.toFixed(3)}s</span>
            </div>
            <div style={styles.timingItem}>
              <span style={styles.timingLabel}>Started:</span>
              <span style={styles.timingValue}>
                {new Date(nlpData.timing.startTime).toLocaleString('en-IE', { dateStyle: 'short', timeStyle: 'medium' })}
              </span>
            </div>
            <div style={styles.timingItem}>
              <span style={styles.timingLabel}>End Time:</span>
              <span style={styles.timingValue}>
                {new Date(nlpData.timing.endTime).toLocaleString('en-IE', { dateStyle: 'short', timeStyle: 'medium' })}
              </span>
            </div>
          </div>
        </div>
      )}

      {/* Distinct extracted figures used as supporting quantitative evidence. */}
      {financialFigures.length > 0 && (
        <div style={styles.section}>
          <h3>
            <i className="bi bi-currency-dollar me-2"></i>
            Financial Figures
          </h3>
          <div style={styles.financialFiguresList}>
            {financialFigures.map((fig, idx) => (
              <div key={idx} style={styles.financialFigureItem}>
                <span style={styles.financialFigureText}>{fig.text}</span>
                <span style={styles.financialFigureMeta}>
                  (chars {fig.start_char}–{fig.end_char})
                </span>
                {fig.context && <div style={styles.financialFigureContext}>{fig.context}</div>}
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  );
}

export default NLPAnalysisOverviewSection;
